<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jurusan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(!$this->session->userdata('mimin_is_login')){
            redirect('auth/signin');
            die();
        }
        $this->load->model('Jurusan_model');
    } 

    /*
     * Listing of jurusan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('jurusan/index?');
        $config['total_rows'] = $this->Jurusan_model->get_all_jurusan_count();
        $this->pagination->initialize($config);

        $data['jurusan'] = $this->Jurusan_model->get_all_jurusan($params);
        
        $data['_view'] = 'jurusan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jurusan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required|max_length[50]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'name' => $this->input->post('name'),
            );
            
            $jurusan_id = $this->Jurusan_model->add_jurusan($params);
            redirect('jurusan/index');
        }
        else
        {            
            $data['_view'] = 'jurusan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jurusan
     */
    function edit($id)
    {   
        // check if the jurusan exists before trying to edit it
        $data['jurusan'] = $this->Jurusan_model->get_jurusan($id);
        
        if(isset($data['jurusan']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required|max_length[50]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'name' => $this->input->post('name'),
                );

                $this->Jurusan_model->update_jurusan($id,$params);            
                redirect('jurusan/index');
            }
            else
            {
                $data['_view'] = 'jurusan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jurusan you are trying to edit does not exist.');
    } 

    /*
     * Deleting jurusan
     */
    function remove($id)
    {
        $jurusan = $this->Jurusan_model->get_jurusan($id);

        // check if the jurusan exists before trying to delete it
        if(isset($jurusan['id']))
        {
            $this->Jurusan_model->delete_jurusan($id);
            redirect('jurusan/index');
        }
        else
            show_error('The jurusan you are trying to delete does not exist.');
    }
    
}
