<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Sikap extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sikap_model');
    }

    /*
     * Listing of sikap
     */
    function index()
    {
        $data['sikap'] = $this->Sikap_model->get_all_sikap();

        $data['_view'] = 'sikap/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sikap
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('name','Name','required');
		$this->form_validation->set_rules('bobot','Bobot','required|max_length[50]');

		if($this->form_validation->run())
        {
            $params = array(
				'name' => $this->input->post('name'),
				'bobot' => $this->input->post('bobot'),
            );

            $sikap_id = $this->Sikap_model->add_sikap($params);
            redirect('sikap/index');
        }
        else
        {
            $data['_view'] = 'sikap/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a sikap
     */
    function edit($id)
    {
        // check if the sikap exists before trying to edit it
        $data['sikap'] = $this->Sikap_model->get_sikap($id);

        if(isset($data['sikap']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('name','Name','required');
			$this->form_validation->set_rules('bobot','Bobot','required|max_length[50]');

			if($this->form_validation->run())
            {
                $params = array(
					'name' => $this->input->post('name'),
					'bobot' => $this->input->post('bobot'),
                );

                $this->Sikap_model->update_sikap($id,$params);
                redirect('sikap/index');
            }
            else
            {
                $data['_view'] = 'sikap/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sikap you are trying to edit does not exist.');
    }

    /*
     * Deleting sikap
     */
    function remove($id)
    {
        $sikap = $this->Sikap_model->get_sikap($id);

        // check if the sikap exists before trying to delete it
        if(isset($sikap['id']))
        {
            $this->Sikap_model->delete_sikap($id);
            redirect('sikap/index');
        }
        else
            show_error('The sikap you are trying to delete does not exist.');
    }

}
