<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_admin extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_admin_model');
    } 

    /*
     * Listing of user_admin
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('user_admin/index?');
        $config['total_rows'] = $this->User_admin_model->get_all_user_admin_count();
        $this->pagination->initialize($config);

        $data['user_admin'] = $this->User_admin_model->get_all_user_admin($params);
        
        $data['_view'] = 'user_admin/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user_admin
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password','Password','required|max_length[32]');
		$this->form_validation->set_rules('username','Username','required|max_length[20]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'username' => $this->input->post('username'),
            );
            
            $user_admin_id = $this->User_admin_model->add_user_admin($params);
            redirect('user_admin/index');
        }
        else
        {            
            $data['_view'] = 'user_admin/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user_admin
     */
    function edit($id)
    {   
        // check if the user_admin exists before trying to edit it
        $data['user_admin'] = $this->User_admin_model->get_user_admin($id);
        
        if(isset($data['user_admin']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('password','Password','required|max_length[32]');
			$this->form_validation->set_rules('username','Username','required|max_length[20]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'username' => $this->input->post('username'),
                );

                $this->User_admin_model->update_user_admin($id,$params);            
                redirect('user_admin/index');
            }
            else
            {
                $data['_view'] = 'user_admin/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user_admin you are trying to edit does not exist.');
    } 

    /*
     * Deleting user_admin
     */
    function remove($id)
    {
        $user_admin = $this->User_admin_model->get_user_admin($id);

        // check if the user_admin exists before trying to delete it
        if(isset($user_admin['id']))
        {
            $this->User_admin_model->delete_user_admin($id);
            redirect('user_admin/index');
        }
        else
            show_error('The user_admin you are trying to delete does not exist.');
    }
    
}
