<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Calon_aslab_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get calon_aslab by id
     */
    function get_calon_aslab($id)
    {
        return $this->db->get_where('calon_aslab',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all calon_aslab count
     */
    function get_all_calon_aslab_count()
    {
        $this->db->from('calon_aslab');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all calon_aslab
     */
    function get_all_calon_aslab($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('calon_aslab')->result_array();
    }
        
    /*
     * function to add new calon_aslab
     */
    function add_calon_aslab($params)
    {
        $this->db->insert('calon_aslab',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update calon_aslab
     */
    function update_calon_aslab($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('calon_aslab',$params);
    }
    
    /*
     * function to delete calon_aslab
     */
    function delete_calon_aslab($id)
    {
        return $this->db->delete('calon_aslab',array('id'=>$id));
    }
}
