<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jurusan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jurusan by id
     */
    function get_jurusan($id)
    {
        return $this->db->get_where('jurusan',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all jurusan count
     */
    function get_all_jurusan_count()
    {
        $this->db->from('jurusan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all jurusan
     */
    function get_all_jurusan($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('jurusan')->result_array();
    }
        
    /*
     * function to add new jurusan
     */
    function add_jurusan($params)
    {
        $this->db->insert('jurusan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jurusan
     */
    function update_jurusan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('jurusan',$params);
    }
    
    /*
     * function to delete jurusan
     */
    function delete_jurusan($id)
    {
        return $this->db->delete('jurusan',array('id'=>$id));
    }
}
