<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Nilai_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get nilai by id
     */
    function get_nilai($id)
    {
        return $this->db->get_where('nilai',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all nilai count
     */
    function get_all_nilai_count()
    {
        $this->db->from('nilai');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all nilai
     */
    function get_all_nilai($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('nilai')->result_array();
    }
        
    /*
     * function to add new nilai
     */
    function add_nilai($params)
    {
        $this->db->insert('nilai',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update nilai
     */
    function update_nilai($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('nilai',$params);
    }
    
    /*
     * function to delete nilai
     */
    function delete_nilai($id)
    {
        return $this->db->delete('nilai',array('id'=>$id));
    }
}
