<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sikap_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sikap by id
     */
    function get_sikap($id)
    {
        return $this->db->get_where('sikap',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all sikap
     */
    function get_all_sikap()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('sikap')->result_array();
    }
        
    /*
     * function to add new sikap
     */
    function add_sikap($params)
    {
        $this->db->insert('sikap',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sikap
     */
    function update_sikap($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('sikap',$params);
    }
    
    /*
     * function to delete sikap
     */
    function delete_sikap($id)
    {
        return $this->db->delete('sikap',array('id'=>$id));
    }
}
