<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_admin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user_admin by id
     */
    function get_user_admin($id)
    {
        return $this->db->get_where('user_admin',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all user_admin count
     */
    function get_all_user_admin_count()
    {
        $this->db->from('user_admin');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all user_admin
     */
    function get_all_user_admin($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('user_admin')->result_array();
    }
        
    /*
     * function to add new user_admin
     */
    function add_user_admin($params)
    {
        $this->db->insert('user_admin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user_admin
     */
    function update_user_admin($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('user_admin',$params);
    }
    
    /*
     * function to delete user_admin
     */
    function delete_user_admin($id)
    {
        return $this->db->delete('user_admin',array('id'=>$id));
    }
}
